apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-web-app
  namespace: game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-web-app
  template:
    metadata:
      labels:
        app: apache-web-app
    spec:
      containers:
      - name: apache-container
        image: alexwhen/docker-2048:latest
        ports:
        - containerPort: 80
