apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: game
spec:
  selector:
    app: apache-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
